export const routesBook = {
  main: () => "/",
  posters: () => "/posters",
  films: () => "/films",
  film: () => "/films/:id",
  media: () => "/media",
  actors: () => "/actors",
  actor: () => "/actor/:id",
  news: () => "/news",
  collections: () => "/collections",
  categories: () => "/categories",
  privacyPolicy: () => "/privacyPolicy",
  dataDeletion: () => "/dataDeletion",
  ratings: () => "/ratings",
  reviews: () => "/reviews",
  favorites: () => "/favorites",
};
